#!/bin/sh
# -*- mode: shell-script; coding: utf-8-emacs-unix; sh-basic-offset: 8; indent-tabs-mode: t -*-
# This code is under Simplified BSD License, see LICENSE for more info
# Copyright (c) 2010, Piotr Karbowski
# All rights reserved.
#
# This code is taken from https://github.com/slashbeast/better-initramfs
# and stripped down (by Arch Linux ARM) to the be tiny and easy to read.

export PATH=/bin

echo '[init] booting'
nsboot

echo '[init] error encountered, copying core file(s) to SD card and rebooting'
mkdir -p /mnt/media
mount /dev/store/media /mnt/media
mkdir -p /mnt/media/nsboot/logs
cp /var/* /mnt/media/nsboot/logs/
sync
reboot
